### ISSUE TITLE
Official and custom built images on HcloudMachineTemplate

### ISSUE THREAD

**Issue by xunleii** [cluster-api-provider-hcloud/cluster-api-provider-hcloud#100]
Firstly, thanks a lot for this Hetzner CAP !

**User Story**

As an operator I would like to use my own built image in order to use other k8s distributions, like k3s (using https://github.com/zawachte-msft/cluster-api-k3s).

**Detailed Description**

I think it could be awesome to use official images or our own built image directly from the `HcloudMachineTemplate`, allowing us more flexibility (for air-gapped cluster).

**Comment by rpahli** [comment]
You can already use your own image with this example:

```
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: test-cluster-control-plane-mt-v1.0.0
spec:
  template:
    spec:
      type: cx21-ceph
      image: https://github.com/rpahli/hetzner-packer/raw/main/images/centos/centos-8_k8s-v1.20.7.tar.gz
```

currently the docs are missing this I think.
