### ISSUE TITLE
MachineHealthChecks are not working

### ISSUE THREAD

**Issue by batistein** [cluster-api-provider-hcloud/cluster-api-provider-hcloud#36]
**What steps did you take and what happened:**
Machine HealthChecks are not working used this configuration:  

```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineHealthCheck
metadata:
  name: cluster-dev-worker-unhealthy-1m
spec:
  clusterName: cluster-dev
  maxUnhealthy: 10%
  nodeStartupTimeout: 5m
  selector:
    matchLabels:
      nodepool: cluster-dev-worker-0
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 60s
  - type: Ready
    status: "False"
    timeout: 60s
```
